import type { Env } from '../env';
import { errorJson, json } from '../lib/http';
import { runGeminiConversation } from './providers/gemini';
import { runOpenAiCompatConversation } from './providers/openai-compat';
import type { ChatMessage, ChatProvider, ChatTurnResult } from './types';

const providers: ChatProvider[] = ['gemini', 'openai', 'openai-compat'];
export function resolveProvider(value: unknown, env: Env): ChatProvider { const candidate = typeof value === 'string' ? value : env.DEFAULT_CHAT_PROVIDER; return providers.includes(candidate as ChatProvider) ? candidate as ChatProvider : 'gemini'; }
export function defaultModelFor(provider: ChatProvider, env: Env): string { if (provider === 'gemini') return env.GEMINI_MODEL || 'gemini-flash-latest'; if (provider === 'openai') return env.OPENAI_MODEL || 'gpt-4o-mini'; return env.OPENAI_COMPAT_MODEL || 'gpt-4o-mini'; }
export function buildSystemPrompt(): string { return 'คุณคือผู้ช่วย AI ของ AI Desk ตอบเป็นภาษาไทยอย่างสุภาพ กระชับ และช่วยแก้ปัญหาให้ผู้ใช้ตามข้อมูลที่มี หากไม่แน่ใจให้บอกตรง ๆ'; }
function resolveTools() { return []; }
function validHistory(value: unknown): ChatMessage[] { if (!Array.isArray(value)) return []; return value.filter((item): item is ChatMessage => Boolean(item) && typeof item === 'object' && ((item as ChatMessage).role === 'user' || (item as ChatMessage).role === 'assistant') && typeof (item as ChatMessage).content === 'string'); }
export async function runChatTurn(message: string, history: ChatMessage[], provider: ChatProvider, model: string, env: Env): Promise<ChatTurnResult> { const messages = [...history, { role: 'user' as const, content: message }]; const tools = resolveTools(); if (provider === 'gemini') return runGeminiConversation(env.GEMINI_API_KEY, model, messages, buildSystemPrompt(), tools); if (provider === 'openai') return runOpenAiCompatConversation('https://api.openai.com/v1', env.OPENAI_API_KEY, model, messages, buildSystemPrompt(), tools); return runOpenAiCompatConversation(env.OPENAI_COMPAT_BASE_URL, env.OPENAI_COMPAT_API_KEY, model, messages, buildSystemPrompt(), tools); }
export async function handleChatRoute(request: Request, env: Env): Promise<Response> { if (request.method !== 'POST') return errorJson('ต้องใช้เมธอด POST', 405); let body: unknown; try { body = await request.json(); } catch { return errorJson('รูปแบบ JSON ไม่ถูกต้อง', 400); } if (!body || typeof body !== 'object' || typeof (body as { message?: unknown }).message !== 'string' || !(body as { message: string }).message.trim()) return errorJson('กรุณาส่ง message ที่ไม่ว่าง', 400); const input = body as { message: string; history?: unknown; provider?: unknown; model?: unknown }; const provider = resolveProvider(input.provider, env); const model = typeof input.model === 'string' && input.model.trim() ? input.model.trim() : defaultModelFor(provider, env); try { const result = await runChatTurn(input.message.trim(), validHistory(input.history), provider, model, env); return json({ reply: result.reply, provider, model, toolTrace: result.toolTrace }); } catch { return json({ reply: 'ไม่สามารถเชื่อมต่อ AI provider ได้ในขณะนี้ กรุณาตรวจสอบการตั้งค่าและลองใหม่อีกครั้ง', provider, model, toolTrace: [] }); } }